Handling validation errors in social auth views.
kodujdlapolski/otm-core pull request #12
Opened 2017-04-12 18:29 UTC by sireliah

Catching exceptions from social_django and showing them in the login page. Please check this.

2017-04-18 15:51 UTC, vevurka requested changes

2017-04-18 15:51 UTC, vevurka commented on opentreemap/treemap/tests/test_auth.py
> +            'https://accounts.google.com/o/oauth2/auth?scope=openid+email+profile&state=zz&redirect_uri=http://testserver/oauth/complete/google-oauth2/&response_type=code&client_id=1',
too long line. why this url?

2017-04-18 15:51 UTC, vevurka commented on opentreemap/treemap/tests/test_auth.py
> +    def test_google_auth_redirect(self, *args):
test for not happy path should be written too.

2017-04-18 15:51 UTC, vevurka commented on opentreemap/treemap/exceptions.py
> +                error_message = _("Sorry, there was a problem with logging you in. "
why we can't get this from translations somehow?

2017-04-18 16:22 UTC, sireliah commented on opentreemap/treemap/tests/test_auth.py
> +            'https://accounts.google.com/o/oauth2/auth?scope=openid+email+profile&state=zz&redirect_uri=http://testserver/oauth/complete/google-oauth2/&response_type=code&client_id=1',
I'll reformat this. This url is used because there is problem with mocking google api. At least I failed to do this.

2017-04-18 16:25 UTC, sireliah commented on opentreemap/treemap/tests/test_auth.py
> +    def test_google_auth_redirect(self, *args):
Actually this is not the happy case, but just redirection. I mean that this view should produce only redirection. But yes, there should be more tests, but authorization api is quite hard to test.

2017-05-09 16:57 UTC, vevurka approved these changes

2017-05-09 17:00 UTC, merged