Translations pl
kodujdlapolski/otm-core pull request #3
Opened 2017-03-18 23:47 UTC by sireliah

Cleaned up a bit the mess in translations. Simplified templates for polish version.

2017-03-19 15:24 UTC, KrzysztofMadejski commented
Do you plan to pull request some changes back to the original?

2017-03-19 15:31 UTC, sireliah commented
No, I'm publishing changes that are fixing incorrect translations that were present in the devel and master. It appears that django "makemessages" command added translations in wrong place. I hope this will be ok now.

2017-03-19 20:58 UTC, vevurka commented on opentreemap/treemap/tests/test_templatetags.py
> +    # TODO: FIXME
what's wrong here?

2017-03-19 20:58 UTC, vevurka requested changes
please answer a question

2017-03-19 21:11 UTC, sireliah commented on opentreemap/treemap/tests/test_templatetags.py
> +    # TODO: FIXME
I had trouble with django.utils.functional.__proxy__ object returned by display_name() function. It appears that proxy is translation object, which can be transformed to unicode. Fixed.

2017-03-20 22:13 UTC, vevurka approved these changes

2017-03-20 22:13 UTC, merged